To do list
dev1980/To-Do-List pull request #1
Opened 2020-02-11 19:10 UTC by dev1980

>Created Todo lists app with OOP principles.
>We use HTML, CSS, JS, and Webpack.
>We add features to create Projects and add a task to each project.

2020-02-11 19:40 UTC, bellom requested changes
## Hi Team :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
Below are part of the checklist for this project, kindly work on these few things listed below;

1. There should be a  'default' project`
![image](https://user-images.githubusercontent.com/31897434/74272251-9dc47400-4d0e-11ea-826d-3a08cbadeb89.png)
https://www.theodinproject.com/courses/javascript/lessons/todo-list

2. **README file, not detailed**. (you can add steps to git clone your repo, necessary installation to setup project locally and live link)

Kindly watch the video tutorial on how to create a live link 👉  [Link](https://www.loom.com/share/76088842a2d14322bbcf65b884f4d42d);

checkout out the below link for help, free free to follow the template from the pathwright
https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/


**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-02-11 19:40 UTC, bellom commented on src/index.js
> +function renderTodo(currProject) {
Let us move this function out.
![image](https://user-images.githubusercontent.com/31897434/74271596-7325eb80-4d0d-11ea-8c5a-3ffc5a7d0208.png)
https://www.theodinproject.com/courses/javascript/lessons/todo-list

2020-02-12 19:38 UTC, Oghenebrume50 requested changes
### STATUS: CHANGES REQUIRED 

Hi Team good job on this project everything works fine now, kudos on making previous suggested changes :+1:  just one thing left to do. I noticed you changed the eslint file
![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/linter_config.png)
[see correct eslint file](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json) 

please make changes and request another review :+1:  

**RAPHAEL NORIODE** :sunglasses:

2020-02-12 19:50 UTC, lekegitrepo commented
We didn't edit/change the eslint file we forget to copy and paste the required one from the linter-config repo

2020-02-12 20:38 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Good luck in the next project :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-02-12 22:04 UTC, merged